PRODUCT_BRAND := BiancaProject
VERSION := 1.4
OTA_VERSION := 11

# Official tag
ifeq ($(BIANCA_OFFICIAL), true)
    BIANCA_BUILDTYPE := OFFICIAL
else
    BIANCA_BUILDTYPE := UNOFFICIAL
endif

ifeq ($(WITH_GAPPS), true)
    BIANCA_VERSION := $(PRODUCT_BRAND)-v$(VERSION)-Gapps-$(BIANCA_BUILDTYPE)-$(BIANCA_BUILD)-$(shell date +%d%m%Y-%H%M)
else
    BIANCA_VERSION := $(PRODUCT_BRAND)-v$(VERSION)-$(BIANCA_BUILDTYPE)-$(BIANCA_BUILD)-$(shell date +%d%m%Y-%H%M)
endif

LINEAGE_VERSION := $(BIANCA_VERSION)
LINEAGE_DISPLAY_VERSION := $(PRODUCT_BRAND)-v$(VERSION)-$(BIANCA_BUILDTYPE)-$(BIANCA_BUILD)
